### ISSUE TITLE
Hey man. What happened to the Ransomware repo?

### ISSUE THREAD

**Issue by Liam6791sadasd** [Senc3951/Backdoor#1]
Hey man. What happened to the Ransomware repo? I was away for a while, sorry. Going through tough times. I figured that I'd hop back on github and do more testing etc, to find out that the repository isn't there anymore...

**Comment by Senc3951** [comment]
I'm sorry to hear that you are having tough times.
I removed the repo from github because people sent me messgaes about using it... but I can privatly share it with you

**Comment by Senc3951** [comment]
You have discord? It would be much more convenient to use
